# Generated by Django 2.1 on 2018-09-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ishopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Seller',
        ),
    ]
