# Generated by Django 2.1 on 2018-09-16 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ishopapp', '0003_auto_20180909_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
