# Generated by Django 2.1 on 2018-09-17 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishopapp', '0004_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Phone', to=settings.AUTH_USER_MODEL),
        ),
    ]
