# Generated by Django 2.1 on 2018-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishopapp', '0005_auto_20180917_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
